algorithm = "gng"
data = "data/dataset1.png"
results_dir = "results/"
lifetime = 30
# max_iter = 
# epochs = 3
# plot_interval = 100
# sampling_without_replacement = true
# neurons_n = 2
# max_neurons = 1000
# eps_b = 0.2
# eps_n = 0.006
# lambda_param = 100
# alpha = 0.5
# decay = 0.99

# [plotting_colors]
# data_color = "0.8"
# neuron_color = "red"
# current_sample_facecolor = "green"
# current_sample_edgecolor = "k"
# connection = "k"
